syntax enable
set number
set ruler
set hlsearch
set background=light
set backspace=indent,eol,start
set nocompatible
set autoindent
set mouse=a
set noexpandtab
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
colors pablo
set guifont=Courier:h18
